### ISSUE TITLE
File/Directory Path too long

### ISSUE THREAD

**Issue by danieldobalian** [Azure-Samples/active-directory-dotnet-webapi-onbehalfof#10]
Sample is close to the max length allowed by NuGet. I think it has something to do with the dependencies tacking on ~100-150 characters. 

Work Around: Use a super short file path.  I had to stick the sample on my desktop.

**Comment by danieldobalian** [comment]
Same problem as here: http://www.morgantechspace.com/2016/01/nuget-install-package-specified-path-is-too-long.html

**Comment by jmprieur** [comment]
This is a classical problem with Windows.
My advise is to clone the repo in C:\repos for instance.
