### ISSUE TITLE
"Internal Server Error" when trying to add item

### ISSUE THREAD

**Issue by Rick-Kirkham** [Azure-Samples/active-directory-dotnet-webapi-onbehalfof#11]
This sample launches and I can log in fine, but when I try to add an item, I get "An error occurred: Internal Server Error" message box.
The error comes from the following line in the `AddTodoItem `method:
`HttpResponseMessage response = await httpClient.PostAsync(todoListBaseAddress + "/api/todolist", content);`
The response object has Status Code 500 and "Internal Server Error".
Also, looking in Fiddler, it seems that the HTTP request is not actually sent or at least it doesn't show up in Fiddler. 
I can see in VS debugger that the request message gets created and it has the access token in the Authorization header.

**Comment by jmprieur** [comment]
you need to debug your service (by running it under debugger, after checking all the "Common Language Runtime Exceptions" in the Debug | Windows | Exception settings pane). This is probably due to an exception somewhere, which you'll discover.
Closing the issue for the moment. feel free to re-open.
