### ISSUE TITLE
What does acquireTokenRedirect do?

### ISSUE THREAD

**Issue by RehanSaeed** [Azure-Samples/active-directory-dotnet-webapi-onbehalfof#15]
I'm trying to understand how to write some simple code to get a token from the `AuthenticationContext`. Based on this sample I've written the following TypeScript:

```
public getToken(clientId: string): Promise<string> {
  return new Promise<string>((resolve, reject) => {
    this.authenticationContext.acquireToken(clientId, (errorDescription: string, token: string, error: string) => {
      if (error) {
        this.authenticationContext.acquireTokenRedirect(clientId, null, null);
      } else if (token) {
        resolve(token);
      }
    });
  });
}
```

What I don't understand is what the `acquireTokenRedirect` is doing and why it is called if `acquireToken` fails. Looking at the documentation, it calls the `callback` function added to the `config` object.

**Comment by jmprieur** [comment]
in [adal.js](https://github.com/AzureAD/azure-activedirectory-library-for-js), acquiretokenRedirect calls Azure Active Directory, which, when the authentication dance has happened in its own HTML pages, redirects to your application with a token (and then the callback is called).
you might want to look at [adal.js](https://github.com/AzureAD/azure-activedirectory-library-for-js), repository to understand how to use it
