### ISSUE TITLE
Can't make it work in my web app

### ISSUE THREAD

**Issue by dariuszbz** [Azure-Samples/active-directory-dotnet-webapi-onbehalfof#16]
Hello,
VS2017, web app, MVC (or forms), with "work or school authentication" type. 
After user login into app, I (the app) want to read vault secrets in the name of the logged in user. Using user authorization. 
Changeling this since few days, and .... i have no idea.
Could you help some how? Just simple example using OOTB (VS2017), how to ready Azure resources in the name of the current user who run and logged in to the web app, please ;).  
All examples run custom api and custom client. i want to use azure api (vault) with my own client on behalf logged in user.

**Comment by jmprieur** [comment]
Hello @dariuszbz : did you have a look at this article? https://docs.microsoft.com/en-us/azure/key-vault/service-to-service-authentication ?

**Comment by manish-shukla01** [comment]
@jmprieur i am trying to follow something similar but getting the error:
{"AADSTS65001: The user or administrator has not consented to use the application with ID 'https://manishtesttenant.onmicrosoft.com/WebApitest1208' named 'WebApi'. Send an interactive authorization request for this user and resource.\r\nTrace ID: e4ce61c4-d55e-4282-9830-c8c5e6380e00\r\nCorrelation ID: 54800dfc-12ef-4a1a-9c23-f6e5fb0c394f\r\nTimestamp: 2017-12-15 00:12:30Z"}
when calling azure rest api on behalf of signed in user. i made sure i added the clientid of the native app into the manifest of the api app.

**Comment by jmprieur** [comment]
Manish, can you please check which application permissions and delegated permissions are needed for your Web API to call the Azure API?
If some of the ones you checked have a Green icon (requires admin), then you would need to have tenant admin (might be you) press the “Grant Permissions” button in the “Required Permissions” blade.
See [integrating applications with Azure Active Directory](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-integrating-applications) in the paragraph named Example of the consent experience, list item numbered 6
