### ISSUE TITLE
Email claim with WindowsAzureActiveDirectoryBearerAuthentication 

### ISSUE THREAD

**Issue by jrmcdona** [Azure-Samples/active-directory-dotnet-webapi-onbehalfof#17]
@jmprieur 
When using UseWindowsAzureActiveDirectoryBearerAuthentication is the only way to get the email claim by using a Graph call?

I was expecting email to already be in the default claims under ClaimsPrincipal object after a user was successfully authenticated.

Thanks

**Comment by jmprieur** [comment]
@jrmcdona ; did you try with the following claim: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn ?
```
(User.FindFirst(ClaimTypes.Upn))?.Value
```

**Comment by jrmcdona** [comment]
@jmprieur 
Just tried that and it comes back null.   I am getting the bearer token from a front end project which uses
UseOpenIdConnectAuthentication and authority of https://login.microsoftonline.com/common

In that project I get all the claims.

However, taking that bearer token and authorizing in my Web Api proejct does authorize fine, but claims I need are not there.

I must have something messed up in my set up or currently the Web Api piece isn't whitelisted correctly to get full claims.
