### ISSUE TITLE
AppCreationScripts broken

### ISSUE THREAD

**Issue by circuitrider** [Azure-Samples/active-directory-dotnet-webapi-onbehalfof#21]
I don't think I'm taking crazy pills, but am I the only one who can't run the AppCreationScripts successfully? I updated PowerShell to v5 and am logging in for the script as an AD global admin. Passing the tenant ID as well to the cleanup and configuration scripts.

There's some things in the script that seem to be just plain wrong. First, on line 266 of Configure.ps1 it has the string "Windows Azure Active Directory" hard coded, which I don't think is right. Shouldn't that be the new service principal created a few lines up? With the hard coded value, nothing returns since nothing exists with that name, resulting in a null ObjectId, breaking the script. So I changed the hardcoded value to be $todoListServiceWebApiName which results in the ObjectId being returned as expected for the discovered object.

But then after that, the next problem happens on line 269 when the call to Set-AzureADApplication is called. The script stops executing after this line, the next Write-Host line on 270 does not print. There is no error message at all displayed, as well.

The objectId is sent with what seems like the right Guid and the only thing that looks weird is that the ResourceAccess property of the object sent to the RequiredResourcesAccess parameter is an empty array. I'm still digging into why this is the case and what would need to be done to get past this problem.

But I'd like to know if I'm missing something obvious and that this is known to be working properly for others, if I can.

**Comment by jmprieur** [comment]
Hello @circuitrider the "Windows Azure Active Directory" dependency is needed as we call the AAD Graph (this is Windows Azure Active Directory") there: https://github.com/Azure-Samples/active-directory-dotnet-webapi-onbehalfof/blob/master/TodoListService/Controllers/TodoListController.cs#L108

this line does the same of the todolist service
https://github.com/Azure-Samples/active-directory-dotnet-webapi-onbehalfof/blob/master/AppCreationScripts/Configure.ps1#L288

Do you have repro steps? which OS do you use ?

**Comment by circuitrider** [comment]
@jmprieur  I'm on Windows Server 2012 R2 on an Azure VM.

The "Windows Azure Active Directory" application name is referring to a Service Principle of that name it is trying to find, made clear by this line 142 in Configuration.ps1
`$sp = Get-AzureADServicePrincipal -Filter "DisplayName eq '$applicationDisplayName'"`

That is where I'm confused, by "dependency" are you saying that I should already have an existing Service Principal by the name of "Windows Azure Active Directory" underneath my targeted tenant? If so, I'm not finding where that gets generated in this repository, nor any other I can find with google.

I followed the directions in the Readme for the solution of this repo as well as the Readme for the AppCreationScripts. 

1) Created new global admin user under AD tenant with a login like username@mytenant.onmicrosoft.com 

2) Ran this powershell command
`$secpasswd = ConvertTo-SecureString "**********!" -AsPlainText -Force`

3) Ran this powershell command
`$mycreds = New-Object System.Management.Automation.PSCredential (“username@mytenant.onmicrosoft.com”, $secpasswd)
. .\Cleanup.ps1 -Credential $mycreds -TenantId "GUID HERE"
. .\Configure.ps1 -Credential $mycreds -TenantId "GUID HERE"`

The cleanup works as expected, and when run by itself I find no trace of this in my dashboard.

But the Configuration.ps1 blows up with this error
`Set-AzureADApplication : Error occurred while executing SetApplication
Code: Request_BadRequest
Message: Invalid value specified for property 'resourceAppId' of resource 'RequiredResourceAccess'.
RequestId: ce84a489-2079-433a-8b79-f977c0aa6fec
DateTimeStamp: Tue, 06 Mar 2018 02:01:31 GMT
Details: PropertyName  - resourceAppId, PropertyErrorCode  - InvalidValue
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed
At C:\Users\circuitrider\code\active-directory-dotnet-webapi-onbehalfof\AppCreationScripts\Configure.ps1:269 char:2
    Set-AzureADApplication -ObjectId $todoListServiceWebApiAadApplica ...
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : NotSpecified: (:) [Set-AzureADApplication], ApiException
     FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD16.PowerShell.SetAppl
   ication`

**Comment by circuitrider** [comment]
It looks like though I'm getting confusing results due to an unrelated issue with the Visual Studio Powershell Interactive Window. It isn't properly reporting errors in the window after subsequent executions as it does running the scripts in normal powershell instances.

**Comment by circuitrider** [comment]
Ok, I have fixed this by creating a new service principal with the name "Windows Azure Active Directory".

I then had to manually edit the manifest and add to the Oauth2Permissions entry a "User.Read" entry. 

The confusion is that the UI for applying settings to the principal in the following manner does not work as I expected: **Settings->Required Permissions->Microsoft Graph->Delegated->"Sign in and read user profile"**

I cannot understand how or why this doesn't alter the manifest to the value I'm expecting, so I might escalate that with Azure support and get clarification.

**Comment by jmprieur** [comment]
@circuitrider : you should not have to create a new service principal for the AAD Graph. It should be in your active directory (unless you or a tenant admin removed it). BTW it has a lot of Oauth2Permissions:
![image](https://user-images.githubusercontent.com/13203188/37054352-8575db7a-2176-11e8-9e3a-b44762952120.png)

I believe that you could re-add it by going to the "Enterprize applications" button for your active directory:
![image](https://user-images.githubusercontent.com/13203188/37054263-4760e0a0-2176-11e8-87fd-b0cc228206e4.png)

Or otherwise create it by adding a service principal (using powershell) for the Azure application of application ID = "00000002-0000-0000-c000-000000000000" (or Object ID = "87227e7c-d218-432e-9908-0503de3fbbee")

Again, this is not a problem with the script, but with the state of your Active Directory.

**Comment by circuitrider** [comment]
Interesting. My subscription is many years old near the launch of azure, not sure what happened in the time since it was created. I don't recall deleting anything like this, but it is possible. Thanks very much for the clarification!
