### ISSUE TITLE
README.md refers to non-existent method - CallGraphAPIOnBehalfOfUser

### ISSUE THREAD

**Issue by itanex** [Azure-Samples/active-directory-dotnet-webapi-onbehalfof#24]
The [README.md:L199](https://github.com/Azure-Samples/active-directory-dotnet-webapi-onbehalfof/blob/master/README.md#L199) refers to a method CallGraphAPIOnBehalfOfUser that should exist in the DbTokenCache.cs file. 

Please update the readme.md file to reflect the appropriate points on interest in this sample.

**Comment by jmprieur** [comment]
Thanks for reporting this, @itanex . I believe that some text got deleted un-intentionally.
We just fixed it.
