### ISSUE TITLE
JS client gives 401 error

### ISSUE THREAD

**Issue by jimoneil** [Azure-Samples/active-directory-dotnet-webapi-onbehalfof#26]
When setting up this example (in two separate clients), the JavaScript client produces an 401 error when invoking the GET api/todolist endpoint.  It's likely a configuration issue, but have not been able to diagnose it.

**Comment by jmprieur** [comment]
Did you try to run the  [App Creation Scripts](https://github.com/Azure-Samples/active-directory-dotnet-webapi-onbehalfof/blob/master/AppCreationScripts/AppCreationScripts.md)

**Comment by robbietapping** [comment]
G’Day, 

My colleague and I for the past 2 days have also been trying to get the v2 of this to work and am
Also receiving the same problem state above by @jimoneil. 

But when we try the v1 version it works perfectly fine.

We have tried the automation configuration scripts and everything is identical. 

We are extremely perplexed at what the problem is. 

We also find the issue when we try and use the api project with manually calling the /authorize end point and the /token endpoints and try with the access token returned to us. Still no dice. 

I have a feeling something is  amiss with a DLL version, or something to do with Token validation. Any ideas around what it could potentially be would be greatly appreciated. I’ve had way too many sleepless nights on ADAL. 

Cheers Robbie

**Comment by jmprieur** [comment]
@robbietapping 
I'm sorry for your frustration. Having Web API protected by the V2 endpoint is recent, and we have not produced all the samples yet.

Just to be sure I understand, you are trying to use the On-behalf-of sample but for an Azure AD V2 application? I'm assuming you want to let user sign-in with their Microsoft personal account? 
If that's the case, you need to use [MSAL.NET](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki#conceptual-documentation), not [ADAL.NET](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki#conceptual-documentation). Please read [Register your application with Azure Active Directory V2](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Register-your-application-with-Azure-Active-Directory) and  [
Differences between ADAL.NET and MSAL.NET applications](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Adal-to-Msal).

We have not yet created a sample for the OBO flow on Azure AD V2. The closest we have is this sample [
Calling a ASP.NET Core Web API from a WPF application using Azure AD V2](https://github.com/azure-samples/active-directory-dotnet-native-aspnetcore-v2) showing how to protect a Web API with Azure AD V2. We'd need to add how you call another API. This is on our backlog

**Comment by jmprieur** [comment]
@jimoneil thanks for the heads-up. I had not read this protocol documentation
so, @robbietapping, it seems that we cannot do OBO from a JavaScript Single Page application in V2 for security reasons.

 @danieldobalian were you aware of this?

**Comment by jimoneil** [comment]
@jmprieur @danieldobalian  FWIW, there are a couple of postings on this in the NDA MVP list for Azure.  Not supporting OBO from a SPA is pretty limiting.

**Comment by robbietapping** [comment]
G'day all,
Sorry for the late response.
I think i may have made a mistake and posted this in the wrong forum to
begin with, as we are just wanting to use the ADAL.js to secure a Angular
JS
front end & .NET Web API against an Organisational Azure AD, whilst using
the token to get tokens and grab info From Sharepoint/Graph/One Drive api's.

I do have a need to talk between two different API's similar to the On
Behalf of flow.

So.. I guess it come back to it... Why does examples to do the above in V1
work and V2 doesnt?
I've read article after article with people having the same issue, but im
taking the stance that im doing something wrong, or have misread something.

Cheers

Robbie

**Comment by hpsin** [comment]
Hi folks - I'm currently removing that documentation on the page you found.  It's not correct.  You can use an id token or an access token from an implicit flow in an OBO flow, with a caveat - if using an id token and you have an open redirect (wildcarded URL in your reply URLs) on your client, it will be rejected. 

To be clear - your scenario is supported, and SPAs should be able to get a token and send it to a middle tier for OBO flows.

**Comment by jmprieur** [comment]
A preliminary version of a V2 OBO sample is available from https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/jmprieur/obo

**Comment by bbbford** [comment]
Hi @jmprieur 

I am trying to accomplish this very thing. Your above link is no longer working. Do you have a V2 OBO sample that you can reference please?

Thanks!

**Comment by jmprieur** [comment]
Sorry @bbbford the link changed. OBO is now available from https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph

**Comment by jmprieur** [comment]
See the new sample: https://github.com/Azure-Samples/ms-identity-aspnet-webapi-onbehalfof
