### ISSUE TITLE
Not working with azure

### ISSUE THREAD

**Issue by armin-o** [Azure-Samples/active-directory-dotnet-webapi-onbehalfof#29]
Here's my setup:
- Run the Configure script with 
$serviceAadApplication = New-AzureADApplication -DisplayName "TodoListService-OBO" `
                                                 ###   -HomePage "https://bfdefaultclientservicetest.azurewebsites.net/" `
                                                   -IdentifierUris "https://$tenantName/TodoListService-OBO" `
                                                   -PasswordCredentials $key `
                                                   -PublicClient $False
- Published to azure (new app pool) 

The page does not comes up  (500/ The page cannot be displayed because an internal server error has occurred.)
Attached remote debugger with all options in CLR Exceptions  enabled -> nothing

Running locally in IIS/VS works as expected

Q: Is this not supposed to run on Azure? If so please provide additional info on how to accomplish this

**Comment by jmprieur** [comment]
Hi @armin-o 
there is a sql database in the sample. you might want to change the connection string to point to an Azure SQL db ?

**Comment by armin-o** [comment]
EF uses an Azure connection already ;)

**Comment by Mrityunjay-Kandwal** [comment]
I have similar problem. I have made my solution exactly as the Todoservice one, yet , it doesn't authorize and keep giving me Authorization denied .

**Comment by jmprieur** [comment]
did you configure auth in the Web hosting experience? (you should not)

**Comment by jmprieur** [comment]
Closing as there is a new sample: https://github.com/Azure-Samples/ms-identity-aspnet-webapi-onbehalfof
