### ISSUE TITLE
Is it possible to use on behalf of flow in multi tenant apps.

### ISSUE THREAD

**Issue by newbieDev01** [Azure-Samples/active-directory-dotnet-webapi-onbehalfof#32]
Is it possible to use on behalf of flow in multi tenant apps.

So to explain it, my web app is a third party app and thee app is registered in a different tenancy. The API part is in our tenancy.
But when we register the web app(in this case the third party has to woory) in app registration how would they give the API permission to select my API?
Or how will they be able to access my app?

Thanks

**Comment by kalyankrishna1** [comment]
Yes it is. The tenant admin has to provision your multi tenant app in their tenant. They can use the various mechanisms provided in [this](https://github.com/Azure-Samples/active-directory-dotnet-webapp-multitenant-openidconnect) sample to do so...
