### ISSUE TITLE
Is it possible to pass through custom claims received in Client APP to your Web API?

### ISSUE THREAD

**Issue by gsatti0830** [Azure-Samples/active-directory-dotnet-webapi-onbehalfof#33]
Is it possible to pass through custom claims received in Client APP to your Web API?

Scenario:
1. Client APP receives a custom claim upon user sign in.
2. When calling Web API, pass this custom claim along instead of re-issuing the same claim.

**Comment by jmprieur** [comment]
Please have a look to the newer v2.0 sample: https://github.com/Azure-Samples/ms-identity-aspnet-webapi-onbehalfof
