### ISSUE TITLE
work with Microsoft account?

### ISSUE THREAD

**Issue by jimbo74** [Azure-Samples/active-directory-dotnet-webapi-onbehalfof#6]
There isn't an explanation of why this doesn't work with a Microsoft account? Can it be made to work with a Microsoft account? if not, why not? Sorry but I'm a newbie with web development and am just starting to look into this. thanks for any help you can offer

**Comment by dshookowsky** [comment]
While following this step-by-step example, I can't assign permissions to the ToDoListService.  searching for the service by name gives me 'NoResults'

**Comment by danieldobalian** [comment]
@jimbo74 This sample supports Azure AD accounts only.  In order to support Azure AD + MSA, you have to use the v2.0 converged endpoint.  Checkout aka.ms/aadv2 or https://github.com/azure-samples and search for v2 samples.
