### ISSUE TITLE
Could not get TodoListService option in Select API

### ISSUE THREAD

**Issue by richmish** [Azure-Samples/active-directory-dotnet-webapi-onbehalfof#7]
I registered TodoListService but not getting option in Configure Permissions while registering client . Point-8
Configure Permissions for your application - in the Settings menu, choose the 'Required permissions' section, click on Add, then Select an API, and type 'TodoListService' in the textbox. Then, click on Select Permissions and select 'Access TodoListService'.

**Comment by michaelchu28** [comment]
I have the same exact issue

**Comment by alixv1** [comment]
Same issue :( , also i don't well understand the TodoListResourceId parameter in TodoListClient. The github sample shows  https://blabla.onmicrosoft.com/TodoListService , should i set this parameter in my application on Azure (welcome page ?  I try both with https://localhost:44321/ and https://blabla.onmicrosoft.com/TodoListService but when i'm connecting with my client i get an error from Azure AD. The applicaiton named "..." was not found in the tenant named blabla.onmicrosoft.com

**Comment by cignum** [comment]
Same issue here!

**Comment by jmprieur** [comment]
This worked for me (tried today).
Closing for now.
